### ISSUE TITLE
ncc@0.11.0 typescript error

### ISSUE THREAD

**Issue by transitive-bullshit** [zeit/ncc#237]
The included [typescript example](https://github.com/zeit/ncc/tree/master/examples/typescript) throws a build error for me using `0.11.0` but compiles fine with `0.9.0`.

```
> yarn
> yarn build
Error: Hash: 68dec8e1900ae0e3b2dd
Version: webpack 5.0.0-alpha.0
Time: 127ms
Built at: 01/22/2019 7:07:23 PM
   Asset      Size  Chunks  Chunk Names
index.js  2.32 KiB   {404}  main
Entrypoint main = index.js
[548] ./index.ts 1.11 KiB {404} [built] [failed] [1 error]

ERROR in ./index.ts
Module build failed (from (webpack)/ncc/loaders/ts-loader.js):
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/tfischer/dev/temp/ncc-test/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:194100)
    at __webpack_require__ (/Users/tfischer/dev/temp/ncc-test/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:216)
    at Object.<anonymous> (/Users/tfischer/dev/temp/ncc-test/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:113665)
    at __webpack_require__ (/Users/tfischer/dev/temp/ncc-test/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:216)
    at Object.<anonymous> (/Users/tfischer/dev/temp/ncc-test/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:210066)
    at __webpack_require__ (/Users/tfischer/dev/temp/ncc-test/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:216)

    at compiler.close.n (/Users/tfischer/dev/temp/ncc-test/node_modules/@zeit/ncc/dist/ncc/index.js:1:399469)
    at _promise0.then._result0 (eval at create (/Users/tfischer/dev/temp/ncc-test/node_modules/@zeit/ncc/dist/ncc/index.js:1:1105949), <anonymous>:13:1)
error Command failed with exit code 1.
```

If I change package.json to have `"@zeit/ncc": "0.9.0"`, the build works as intended.

I was getting this error in a more complicated scenario, so I tried the built-in typescript example and got the same results.

I'm guessing this was introduced in https://github.com/zeit/ncc/commit/208cdc0d3de40d4409f960f611841deb8013d62b.

I do have `typescript` installed globally. `tsc --version` yields `3.2.4`.

node: v10.3.0
yarn: 1.13.0
macOS High Sierra 10.13.6

cc @guybedford @rauchg

**Comment by samkcarlile** [comment]
I'm having this exact issue. Same versions on everything except I'm using NPM, so it's definitely not specific to Yarn

**Comment by samkcarlile** [comment]
Try installing `typescript` locally, that may have been my issue (I thought I had it installed local previously). @transitive-bullshit

**Comment by transitive-bullshit** [comment]
Indeed, running `yarn add --dev typescript` locally resolved the issue, but the bug should still be fixed.

Thanks @samkcarlile!

**Comment by Foxhunt** [comment]
I have the same issue.

node: v10.15.0
ncc: 0.11.0
tsc: 3.2.4

ncc is installed globally.

Installing typescript globally solves it for me. Installing it locally gives me the error.

Installing both locally and running ncc via npx works as well.

Seems like they must both be installed at the same location.

**Comment by mikaelbr** [comment]
Looks like the issue might stems from here https://github.com/zeit/ncc/blob/master/src/loaders/ts-loader.js#L21 which after #233 is no longer working. Looks like `require.resolve` might cause some issues here if you want to use local `./typescript.js`. Not on my pc right now so can't test/verify myself. But maybe something like changing from

```js
const tsId = require.resolve("typescript");
```

to 

```js
const tsId = getTsId();

// ...
function getTsId() {
  try {
    return require.resolve('typescript');
  }
  catch (e) {
    return require.resolve(__dirname + "/../../dist/ncc/typescript/typescript.js');
  }
}
```
